import type { Metadata } from "next";

import "./globals.css";
import MainProvider from "@/provider/MainProvider";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "aos/dist/aos.css";
import ScrollToTopComponent from "@/components/common/ScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark ">
      <body className="">
        <ScrollToTopComponent />
        <ToastContainer />

        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
